service: collie-frontend

custom:
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  environment:
    BUCKET_WEBSITE_NAME: ${env:BUCKET_WEBSITE_NAME}
    DOMAIN_NAME: ${env:DOMAIN_NAME}
    HOSTED_ZONE_ID: ${env:HOSTED_ZONE_ID}

functions:

resources:
  - ${file(resources/s3-bucket.yml)}
  - ${file(resources/certificate.yml)}
  - ${file(resources/cloudfront.yml)}
  - ${file(resources/dns.yml)}
