Resources:
  DNS:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId:
        Ref: ${self:provider.environment.HOSTED_ZONE_ID}
      RecordSets:
        - Name:
            Ref: ${self:provider.environment.DOMAIN_NAME}
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt Website.DomainName
