Resources:
  Website:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Join:
          [
            '-',
            [
              { 'Fn::Sub': '${self:provider.environment.BUCKET_WEBSITE_NAME}' },
              { 'Fn::Sub': '${self:custom.stage}' },
            ],
          ]
      WebsiteConfiguration:
        ErrorDocument: index.html
        IndexDocument: index.html
Outputs:
  WebsiteURL:
    Value: !GetAtt Website.WebsiteURL
  WebSiteBucket:
    Value: !Ref Website
