Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        ErrorDocument: index.html
        IndexDocument: index.html
Outputs:
  WebsiteURL:
    Value: !GetAtt S3Bucket.WebsiteURL
  WebSiteBucket:
    Value: !Ref S3Bucket
