Resources:
  Website:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        ErrorDocument: index.html
        IndexDocument: index.html
  Outputs:
    WebSiteUrl:
      Value: !GetAtt 'S3Bucket.WebsiteURL'
    WebSiteBucket:
      Value: !Ref Website
